### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by traysub** [mx0c/Corsair-Headset-Battery-Overlay#1]
Please explain how to start this Overlay, i am new to this.

**Comment by mx0c** [comment]
Hey, you should be able to just download the executable from: https://github.com/mx0c/Corsair-Void-Pro-Battery-Overlay/releases/tag/0.0.1. The application is very new so if you encounter any Problems let me know :).

**Comment by traysub** [comment]
First of all, many thanks for the help. I think it's great that someone makes all the effort to create something like that.
when starting the program, however, "couldnt find device" is displayed in the overlay because I am using a Corsair Void Elite.
Would it be possible to reprogram it for the Void Elite without much effort? I would be willing to help as best I can.

**Comment by mx0c** [comment]
Hmm im not sure if the method i used does work for your headset. Do you have the Project setup in an IDE ?

**Comment by traysub** [comment]
I opened the project under Visual Studio and saw in the BatteryReader.cs file that under "private const int PID = 0x0a14;" the value must be changed to "0x0a55".  I just don't know how to create an .exe file after changing the value.

**Comment by mx0c** [comment]
You can build a standalone windows executable with: `dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true` Have you already tested the functionality with the right PID for your device?
