### ISSUE TITLE
Works with the HS70 Pro: device details

### ISSUE THREAD

**Issue by fluffynuts** [mx0c/Corsair-Headset-Battery-Overlay#10]
Hi

I've forked your repo for my own purposes - thanks - but wanted to report back that this code also works with the HS70 Pro headset, which has a different device id (apparently) from the HS70 vanilla (:

I added this to `predefined_configurations.json` for easier support than entering the device id:
```json
	{
		"name": "CORSAIR HS70 PRO Wireless Gaming Headset",
		"PID": "0A4F"
	}
```

hope this helps (: I know that your intent is to have an overlay which shows over things - my use-case is a little different: I'd prefer an icon in the tray only, but I've modified my fork to keep your overlay and do the tray icon - I'll create a PR shortly if you like; I'm about to do a more "abstract" fork, leaning on the device comms part and making something without WPF requirements which only does the systray, because that would suit me better (:

**Comment by mx0c** [comment]
Hi, your changes look great! Thank You. Gonna test and merge it later :)

**Comment by mx0c** [comment]
I have noticed, when changing to image mode, the button in the tray menu isn't updated anymore. Also maybe decoupling the icon functionalities in a separate class would be good.  If you want you can work on these bugs/refactorings. If not I'll do it. Other than that, I really like your changes :) Cheers.

**Comment by fluffynuts** [comment]
I'll see if I get a gap some time soon - got a few things piling up for when I'm on leave.
