### ISSUE TITLE
[Feature Request] Add multiple predefined PIDs 

### ISSUE THREAD

**Issue by SaifAqqad** [mx0c/Corsair-Headset-Battery-Overlay#4]
Thank you for making this, it works really well with my HS70, I only had to change the PID to `0A38` (I found it using [this site](https://www.driverscloud.com/en/drivers/manufacturercat/557-23-1/corsair-multimedia-cards)) 
So maybe you could add the ability to choose a device that's known to work with this by adding more predefined PIDs?

Also I did a bit of testing with the data returned by the device
I noticed that `data[4]` is `5` only when the headset is charging but not full, when it gets full it becomes `4`, when it's connected but not plugged in it's `1` and when it's disconnected its `0`
but I'm not sure if it's the same for all corsair devices

**Comment by mx0c** [comment]
Thanks for your feedback, this is a great idea! Probably gonna implement this soon.
