### ISSUE TITLE
Reverse Engineering methodology

### ISSUE THREAD

**Issue by bad5ect0r** [mx0c/Corsair-Headset-Battery-Overlay#9]
Hello,

Many thanks for building this. I was about to start reverse engineering how iCUE was pulling the battery level but was running into several roadblocks. That's when I discovered your project. Would you be kind enough to provide insight into how you figured out the USB protocol for retrieving the battery level?

Kind regards

**Comment by mx0c** [comment]
Hi,

When I started working on this project I tried to read out memory from the ICUE software but this didn't work reliably. Then I looked for already existing projects similar to what I wanted to do. I discovered a project which had support for a lot of headsets. Sadly I can't remember the name of the project... I'm not sure how they figured out what data to send to the headset to get the battery level. I guess they used either some kind of sniffing or reverse engineered the ICUE software which seems to be quite a hard task.
